### ISSUE TITLE
No restrictions can be set without preventing the function

### ISSUE THREAD

**Issue by DocBrown101** [linuxserver/docker-smokeping#102]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
------------------------------

## Expected Behavior
For safety and performance reasons, general restrictions should be possible.

## Current Behavior
As soon as a limit is set, e.g. mem_limit: 256m, no further data is recorded.

## Steps to Reproduce
Simply enter one of the following values in the docker-compose file:
- cpu_shares: 250
- pids_limit: 100
- mem_limit: 256m
- mem_reservation: 64m
or
security_opt:
apparmor:docker-default
no-new-privileges

## Environment
**OS:** Debian GNU/Linux 10 (buster)
**CPU architecture:** x86_64
**How docker service was installed:**
With the installation script from docker.

## Command used to create docker container (compose)
```yaml
---
version: "2.1"
services:
  smokeping:
    image: ghcr.io/linuxserver/smokeping
    container_name: smokeping
    mem_limit: 256m
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - </path/to/smokeping/config>:/config
      - </path/to/smokeping/data>:/data
    ports:
      - 80:80
    restart: unless-stopped
```

## Docker logs
Unfortunately no errors are shown in the log.
