### ISSUE TITLE
no data in smokeping

### ISSUE THREAD

**Issue by sander816** [linuxserver/docker-smokeping#120]
i installed sokeping with the following docker-compose file:
```
---
version: "2"
services:
  smokeping:
    image: lscr.io/linuxserver/smokeping
    container_name: smokeping
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /mnt/usb/hassio_dockers/smokeping/config:/config
      - /mnt/usb/hassio_dockers/smokeping/data:/data
    ports:
      - 82:80
    restart: unless-stopped
```

i waited several hours, but still there are no charts coming up. Data folder is empty, config folder is filled with configs etc.

this is what i see in the logfile:
```
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------


@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

Your DockerHost is most likely running an outdated version of libseccomp

To fix this, please visit https://docs.linuxserver.io/faq#libseccomp

Some apps might not behave correctly without this

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
[cont-init.d] 30-config: exited 0.
[cont-init.d] 90-custom-folders: executing...
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-files: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
AH00558: httpd: Could not reliably determine the server's fully qualified domain                                                                        name, using 172.18.0.2. Set the 'ServerName' directive globally to suppress this message
WARNING: Hostname 'ipv6.google.com' does currently not resolve to an IPv4 address
```
i am running debian stretch
