### ISSUE TITLE
No data from fping

### ISSUE THREAD

**Issue by NoxInmortus** [linuxserver/docker-smokeping#124]
Using fping probe there does not seems to have any data collected
It may come from that:
```
root@e8add671f9a1:/# ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8): 56 data bytes
64 bytes from 8.8.8.8: seq=0 ttl=114 time=9.014 ms
64 bytes from 8.8.8.8: seq=1 ttl=114 time=9.057 ms
^C
--- 8.8.8.8 ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max = 9.014/9.035/9.057 ms
root@e8add671f9a1:/# sudo -u abc /usr/sbin/fping 8.8.8.8
/usr/sbin/fping: can't create socket (must run as root?)
```

Defaut Probes file contains:
```
+ FPing
binary = /usr/sbin/fping
```

Did not tried FPing6 but expect the same.

------------------------------

## Expected Behavior
Data should be visible in smokeping interface

## Current Behavior
No data

## Steps to Reproduce
1. Setup standard smokeping
2. Edit Targets file:
```
*** Targets ***
probe = FPing
menu = Top
title = Network Latency Grapher
remark = Welcome to Smokeping. \
         Here you will learn all about the latency of our network.

+ Network
menu = Net latency
title = Network latency (ICMP pings)
++ Google
host = 8.8.8.8
```
3. restart

## Environment
**OS:** Debian 10 64 bits
**CPU architecture:** x86_64
**How docker service was installed:** From official repository

## Command used to create docker container (run/create/compose/screenshot)
```
# Using ansible
  - name: smokeping
    image: lscr.io/linuxserver/smokeping
    restart_policy: unless-stopped
    security_opts:
      - no-new-privileges=true
    purge_networks: true
    networks_cli_compatible: true
    networks:
      - name: net-traefik
        aliases:
          - smokeping.{{ template_docker_fqdn }}
    volumes:
      - smokeping-conf:/config
      - smokeping-data:/data
    env:
      TZ: 'UTC'
      PUID: '1000'
      PGID: '1000'
    labels:
      traefik.enable: 'true'
      traefik.docker.network: net-traefik
      traefik.http.routers.smokeping-http.entrypoints: http
      traefik.http.routers.smokeping-http.rule: Host(`smokeping.{{ template_docker_fqdn }}`)
      traefik.http.routers.smokeping-https.entrypoints: https
      traefik.http.routers.smokeping-https.rule: Host(`smokeping.{{ template_docker_fqdn }}`)
      traefik.http.routers.smokeping-https.tls: 'true'
      traefik.http.routers.smokeping-https.tls.options: 'default'
```

## Docker logs
```
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 02-tamper-check: executing...
[cont-init.d] 02-tamper-check: exited 0.
[cont-init.d] 10-adduser: executing...
usermod: no changes

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
[cont-init.d] 30-config: exited 0.
[cont-init.d] 90-custom-folders: executing...
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-files: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.21.0.4. Set the 'ServerName' directive globally to suppress this message
### assuming you are using an fping copy reporting in milliseconds
### parsing dig output...OK
### assuming you are using an fping copy reporting in milliseconds
Smokeping version 2.007003 successfully launched.
Entering multiprocess mode.
No targets defined for probe FPing6, skipping.
No targets defined for probe DNS, skipping.
Child process 344 started for probe FPing.
All probe processes started successfully.
FPing: probing 4 targets with step 300 s and offset 160 s.
```
