### ISSUE TITLE
How do we configure the container to run as a slave ?

### ISSUE THREAD

**Issue by Thatdarkone** [linuxserver/docker-smokeping#76]
Using this docker image, how do you run the container as a slave ?
We already have a master running on another host somewhere else.

**Comment by kplimack** [comment]
@Thatdarkone seems like this isnt a way to do that given how this was setup.  An entrypoint script that flipped the modes between server and slave would be a very easy way to add that functionality

**Comment by thelamer** [comment]
The purpose of this container is to run a standalone installation.

**Comment by Creling** [comment]
Thanks for your work first, which benefits me a lot. @thelamer 
And, is it possible to create another smokeping image that runs in slave model?

**Comment by kplimack** [comment]
i deployed this with kubernetes.  it was pretty trivial to pass different args to the masters/slaves and build a distributed smokeping setup

```
        env:
          - name: TZ
            value: "America/Denver"
          - name: SMOKEPING_MODE
            value: SLAVE
          - name: MASTER_URL
            value: "https://smokeping-master.myorg.com/smokeping/"
```
