### ISSUE TITLE
Probes are not recognized

### ISSUE THREAD

**Issue by kplimack** [linuxserver/docker-smokeping#77]
I'm trying to use this container in kubernetes, I'm mounting a custom Targets and Probes file into /config.  My targets are loaded properly, but when I use any probe besides `fping`, it says it doesn't recognize the probe.  

```
ERROR: /config/Targets, line 28: probe must be defined before the host or any probe variables
```

It looks like Probes are loaded before Targets
```
root@smokeping-75d64fb5c8-jtzbs:/root# cat /etc/smokeping/config
@include /config/General
@include /config/Alerts
@include /config/Database
@include /config/Presentation
@include /config/Probes
@include /config/Slaves
@include /config/Targets
```

```
root@smokeping-75d64fb5c8-jtzbs:/root# cat /config/Probes
*** Probes ***

+ Curl
binary = /usr/bin/curl
urlformat = http://%host%/

+ FPing
binary = /usr/sbin/fping
blazemode = true

+ TCPPing

binary = /usr/bin/tcpping # mandatory
forks = 5
offset = 50%
step = 300
timeout = 15
pings = 5
port = 80

+ DNS
binary = /usr/bin/dig
```

```
root@smokeping-75d64fb5c8-jtzbs:/root# head -n 40 /config/Targets
*** Targets ***

probe = FPing

menu = Top
title = Network Latency Grapher
remark = Welcome to the SmokePing website of b0rked-derp Company.          Here you will learn all about the latency of our network.

+ AutoScaling
menu = AutoScaling
title = AutoScaling

++ AutoScaling
menu = AutoScaling
title = Overall AutoScaling Performance
host = /AutoScaling/us-east-1-icmp /AutoScaling/us-east-1-tcp /AutoScaling/us-east-2-icmp /AutoScaling/us-east-2-tcp /AutoScaling/us-west-1-icmp /AutoScaling/us-west-1-tcp /AutoScaling/us-west-2-icmp /AutoScaling/us-west-2-tcp


++ us-east-1-icmp
menu = us-east-1-icmp
title = us-east-1-icmp
host = autoscaling.us-east-1.amazonaws.com

++ us-east-1-tcp
menu = us-east-1-tcp
title = us-east-1-tcp
host = autoscaling.us-east-1.amazonaws.com
probe = TCPPing

++ us-east-2-icmp
menu = us-east-2-icmp
title = us-east-2-icmp
host = autoscaling.us-east-2.amazonaws.com

++ us-east-2-tcp
menu = us-east-2-tcp
title = us-east-2-tcp
host = autoscaling.us-east-2.amazonaws.com
probe = TCPPing
```

```
│ smokeping-75d64fb5c8-jtzbs:smokeping ERROR: /config/Targets, line 28: probe must be defined before the host or any probe variables                                                                                                         │
│ smokeping-75d64fb5c8-jtzbs:smokeping ERROR: /config/Targets, line 28: probe must be defined before the host or any probe variables                                                                                                         │
│ smokeping-75d64fb5c8-jtzbs:smokeping ERROR: /config/Targets, line 28: probe must be defined before the host or any probe variables                                                                                                         │
│ smokeping-75d64fb5c8-jtzbs:smokeping ERROR: /config/Targets, line 28: probe must be defined before the host or any probe variables                                                                                                         │
│ smokeping-75d64fb5c8-jtzbs:smokeping ERROR: /config/Targets, line 28: probe must be defined before the host or any probe variables                                                                                                         │
│ smokeping-75d64fb5c8-jtzbs:smokeping ERROR: /config/Targets, line 28: probe must be defined before the host or any probe variables                                                                                                         │
│ smokeping-75d64fb5c8-jtzbs:smokeping ERROR: /config/Targets, line 28: probe must be defined before the host or any probe variables                                                                                                         │
│ smokeping-75d64fb5c8-jtzbs:smokeping ERROR: /config/Targets, line 28: probe must be defined before the host or any probe variables
```

```
cat deploy/deployment.yaml
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: smokeping-data
  labels:
    k8s-app: smokeping
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: smokeping
  labels:
    k8s-app: smokeping
spec:
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: smokeping
    spec:
      containers:
      - name: smokeping
        image: linuxserver/smokeping
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
          - name: TZ
            value: "America/New_York"
        volumeMounts:
        - name: smokeping-targets
          mountPath: /config/Targets
          subPath: Targets
        - name: smokeping-probes
          mountPath: /config/Probes
          subPath: Probes
        - mountPath: "/data"
          name: data
      volumes:
        - name: smokeping-targets
          configMap:
            name: smokeping-targets
        - name: smokeping-probes
          configMap:
            name: smokeping-probes
        - name: data
          persistentVolumeClaim:
            claimName: smokeping-data
```
