### ISSUE TITLE
Enable IPv6 connection

### ISSUE THREAD

**Issue by timdream** [linuxserver/docker-smokeping#93]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior

I should be able to ping an IPv6 address.

## Current Behavior

It doesn't: `2001:4860:4860::8888: error while sending ping: Address not available`

## Steps to Reproduce

Set up a IPv6 probe like this

Set up a `FPing6` probe like

```++ GoogleDNSv6

menu = Google DNS v6
title = Google DNS v6
probe = FPing
host = 2001:4860:4860::8888
```

(`Fping` is unified, no need to call `Fping6`)

## Environment
**OS:** Ubuntu 20.06
**CPU architecture:** x86_64
**How docker service was installed:**  Setup with docker-compose.

## Command used to create docker container (run/create/compose/screenshot)
```
version: "2.1"
services:
  smokeping:
    image: linuxserver/smokeping
    container_name: smokeping
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - /opt/docker-smokeping/config:/config
      - /opt/docker-smokeping/data:/data
    ports:
      - "127.0.0.1:8001:80"
    restart: unless-stopped
```

## Note

I understand it takes more setup in the container to enable IPv6. The possible fix of this issue is some verified descriptions of how one can enable IPv6, not necessarily a change in `Dockerfile`.
